from dataclasses import dataclass
from enum import Enum
from typing import Optional


class FieldCategory(Enum):
    IDENTITY = "identity"
    ADDRESS = "address"
    FINANCIAL = "financial"
    EMPLOYMENT = "employment"
    LEGAL = "legal"
    MEDICAL = "medical"
    EDUCATION = "education"
    TRAVEL = "travel"
    INSURANCE = "insurance"
    TAX = "tax"
    SOCIAL = "social"
    CONTACT = "contact"
    PROPERTY = "property"
    VEHICLE = "vehicle"
    DIGITAL = "digital"
    FAMILY = "family"
    IMMIGRATION = "immigration"
    BANKING = "banking"
    PENSION = "pension"
    UTILITY = "utility"
    OTHER = "other"


class FieldSensitivity(Enum):
    PUBLIC = "public"
    INTERNAL = "internal"
    SENSITIVE = "sensitive"
    CRITICAL = "critical"


@dataclass
class FieldDefinition:
    key: str
    label_en: str
    label_de: str
    category: FieldCategory
    sensitivity: FieldSensitivity
    frozen: bool = False
    has_expiry: bool = False
    aliases: Optional[list[str]] = None
    regex: Optional[str] = None
    example: Optional[str] = None


FIELD_REGISTRY: dict[str, FieldDefinition] = {
    # ── IDENTITY ──────────────────────────────────────────────────────────────
    "full_name": FieldDefinition(
        key="full_name",
        label_en="Full Name",
        label_de="Vollständiger Name",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        frozen=True,
        aliases=["name", "vor- und nachname", "name complet"],
        example="Max Mustermann",
    ),
    "first_name": FieldDefinition(
        key="first_name",
        label_en="First Name",
        label_de="Vorname",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        frozen=True,
        aliases=["vorname", "given name", "prénom"],
        example="Max",
    ),
    "last_name": FieldDefinition(
        key="last_name",
        label_en="Last Name",
        label_de="Nachname",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        frozen=True,
        aliases=["nachname", "familienname", "surname", "nom"],
        example="Mustermann",
    ),
    "middle_name": FieldDefinition(
        key="middle_name",
        label_en="Middle Name",
        label_de="Zweiter Vorname",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["zweiter vorname", "middle initial"],
    ),
    "birth_name": FieldDefinition(
        key="birth_name",
        label_en="Birth Name",
        label_de="Geburtsname",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        frozen=True,
        aliases=["geburtsname", "maiden name", "née"],
    ),
    "date_of_birth": FieldDefinition(
        key="date_of_birth",
        label_en="Date of Birth",
        label_de="Geburtsdatum",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.CRITICAL,
        frozen=True,
        aliases=["geburtsdatum", "dob", "né le", "born"],
        regex=r"\d{2}[.\-/]\d{2}[.\-/]\d{4}",
        example="01.01.1990",
    ),
    "place_of_birth": FieldDefinition(
        key="place_of_birth",
        label_en="Place of Birth",
        label_de="Geburtsort",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        frozen=True,
        aliases=["geburtsort", "birthplace", "lieu de naissance"],
        example="Berlin",
    ),
    "country_of_birth": FieldDefinition(
        key="country_of_birth",
        label_en="Country of Birth",
        label_de="Geburtsland",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        frozen=True,
        aliases=["geburtsland", "country of origin"],
    ),
    "nationality": FieldDefinition(
        key="nationality",
        label_en="Nationality",
        label_de="Staatsangehörigkeit",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        frozen=True,
        aliases=["staatsangehörigkeit", "nationalité", "citizenship"],
        example="Deutsch",
    ),
    "second_nationality": FieldDefinition(
        key="second_nationality",
        label_en="Second Nationality",
        label_de="Zweite Staatsangehörigkeit",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["doppelte staatsangehörigkeit", "dual citizenship"],
    ),
    "gender": FieldDefinition(
        key="gender",
        label_en="Gender",
        label_de="Geschlecht",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["geschlecht", "sex", "sexe"],
        example="M / F / D",
    ),
    "marital_status": FieldDefinition(
        key="marital_status",
        label_en="Marital Status",
        label_de="Familienstand",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["familienstand", "civil status", "état civil"],
        example="ledig / verheiratet / geschieden",
    ),
    "religion": FieldDefinition(
        key="religion",
        label_en="Religion",
        label_de="Religion",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["konfession", "confession"],
    ),
    "height": FieldDefinition(
        key="height",
        label_en="Height",
        label_de="Größe",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["größe", "körpergröße"],
        regex=r"\d{3}\s?cm",
        example="180 cm",
    ),
    "eye_color": FieldDefinition(
        key="eye_color",
        label_en="Eye Color",
        label_de="Augenfarbe",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["augenfarbe", "couleur des yeux"],
        example="blau / braun / grün",
    ),
    "signature": FieldDefinition(
        key="signature",
        label_en="Signature",
        label_de="Unterschrift",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["unterschrift", "signature"],
    ),
    # ── TRAVEL DOCUMENTS ──────────────────────────────────────────────────────
    "passport_number": FieldDefinition(
        key="passport_number",
        label_en="Passport Number",
        label_de="Reisepassnummer",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.CRITICAL,
        frozen=True,
        has_expiry=True,
        aliases=["reisepassnummer", "pass-nr", "passport no"],
        regex=r"[A-Z]{1,2}[0-9]{6,9}",
        example="C01X00T47",
    ),
    "passport_expiry": FieldDefinition(
        key="passport_expiry",
        label_en="Passport Expiry",
        label_de="Reisepass Ablaufdatum",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.CRITICAL,
        has_expiry=True,
        aliases=["gültig bis", "date of expiry", "expiry date"],
        regex=r"\d{2}[.\-/]\d{2}[.\-/]\d{4}",
    ),
    "passport_issue_date": FieldDefinition(
        key="passport_issue_date",
        label_en="Passport Issue Date",
        label_de="Ausstellungsdatum Reisepass",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["ausstellungsdatum", "date of issue"],
    ),
    "passport_issuing_country": FieldDefinition(
        key="passport_issuing_country",
        label_en="Issuing Country",
        label_de="Ausstellendes Land",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["ausstellendes land", "country of issue"],
    ),
    "passport_issuing_authority": FieldDefinition(
        key="passport_issuing_authority",
        label_en="Issuing Authority",
        label_de="Ausstellende Behörde",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["ausstellende behörde", "authority"],
    ),
    "mrz_line1": FieldDefinition(
        key="mrz_line1",
        label_en="MRZ Line 1",
        label_de="MRZ Zeile 1",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.CRITICAL,
        regex=r"[A-Z0-9<]{44}",
    ),
    "mrz_line2": FieldDefinition(
        key="mrz_line2",
        label_en="MRZ Line 2",
        label_de="MRZ Zeile 2",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.CRITICAL,
        regex=r"[A-Z0-9<]{44}",
    ),
    "visa_number": FieldDefinition(
        key="visa_number",
        label_en="Visa Number",
        label_de="Visumnummer",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.CRITICAL,
        has_expiry=True,
        aliases=["visumnummer", "visa no"],
    ),
    "visa_type": FieldDefinition(
        key="visa_type",
        label_en="Visa Type",
        label_de="Visumart",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["visumart", "type of visa"],
        example="D / C / Schengen",
    ),
    "visa_expiry": FieldDefinition(
        key="visa_expiry",
        label_en="Visa Expiry",
        label_de="Visum Ablaufdatum",
        category=FieldCategory.TRAVEL,
        sensitivity=FieldSensitivity.CRITICAL,
        has_expiry=True,
        aliases=["visum gültig bis"],
    ),
    # ── NATIONAL ID ───────────────────────────────────────────────────────────
    "id_number": FieldDefinition(
        key="id_number",
        label_en="ID Number",
        label_de="Ausweisnummer",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.CRITICAL,
        frozen=True,
        has_expiry=True,
        aliases=["ausweisnummer", "personalausweisnummer", "id no"],
        regex=r"[A-Z0-9]{9,10}",
    ),
    "id_expiry": FieldDefinition(
        key="id_expiry",
        label_en="ID Expiry",
        label_de="Ausweis Ablaufdatum",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.CRITICAL,
        has_expiry=True,
        aliases=["gültig bis", "expiry"],
    ),
    "id_issue_date": FieldDefinition(
        key="id_issue_date",
        label_en="ID Issue Date",
        label_de="Ausstellungsdatum Ausweis",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["ausstellungsdatum"],
    ),
    "id_issuing_authority": FieldDefinition(
        key="id_issuing_authority",
        label_en="ID Issuing Authority",
        label_de="Ausstellende Behörde",
        category=FieldCategory.IDENTITY,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["ausstellende behörde", "ausstellungsbehörde"],
    ),
    # ── IMMIGRATION ───────────────────────────────────────────────────────────
    "permit_number": FieldDefinition(
        key="permit_number",
        label_en="Permit Number",
        label_de="Aufenthaltstitel-Nummer",
        category=FieldCategory.IMMIGRATION,
        sensitivity=FieldSensitivity.CRITICAL,
        has_expiry=True,
        aliases=["aufenthaltstitel-nr", "permit no"],
    ),
    "permit_type": FieldDefinition(
        key="permit_type",
        label_en="Permit Type",
        label_de="Aufenthaltstitel Art",
        category=FieldCategory.IMMIGRATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["aufenthaltserlaubnis", "niederlassungserlaubnis", "blaue karte"],
        example="Aufenthaltserlaubnis / Niederlassungserlaubnis / Blaue Karte EU",
    ),
    "permit_expiry": FieldDefinition(
        key="permit_expiry",
        label_en="Permit Expiry",
        label_de="Aufenthaltstitel Ablaufdatum",
        category=FieldCategory.IMMIGRATION,
        sensitivity=FieldSensitivity.CRITICAL,
        has_expiry=True,
        aliases=["gültig bis", "aufenthaltstitel ablauf"],
    ),
    "permit_issue_date": FieldDefinition(
        key="permit_issue_date",
        label_en="Permit Issue Date",
        label_de="Ausstellungsdatum Aufenthaltstitel",
        category=FieldCategory.IMMIGRATION,
        sensitivity=FieldSensitivity.SENSITIVE,
    ),
    "permit_issuing_authority": FieldDefinition(
        key="permit_issuing_authority",
        label_en="Permit Issuing Authority",
        label_de="Ausländerbehörde",
        category=FieldCategory.IMMIGRATION,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["ausländerbehörde", "immigration office"],
    ),
    "permit_conditions": FieldDefinition(
        key="permit_conditions",
        label_en="Permit Conditions",
        label_de="Auflagen",
        category=FieldCategory.IMMIGRATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["auflagen", "nebenbestimmungen", "conditions"],
    ),
    "entry_date": FieldDefinition(
        key="entry_date",
        label_en="Entry Date",
        label_de="Einreisedatum",
        category=FieldCategory.IMMIGRATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["einreisedatum", "date of entry"],
    ),
    "asylum_number": FieldDefinition(
        key="asylum_number",
        label_en="Asylum Number",
        label_de="Aktenzeichen Asyl",
        category=FieldCategory.IMMIGRATION,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["aktenzeichen", "bamf-nummer"],
    ),
    "registration_number": FieldDefinition(
        key="registration_number",
        label_en="Registration Number",
        label_de="Registriernummer",
        category=FieldCategory.IMMIGRATION,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["registriernummer", "ankunftsnachweis"],
    ),
    # ── ADDRESS ───────────────────────────────────────────────────────────────
    "address": FieldDefinition(
        key="address",
        label_en="Full Address",
        label_de="Vollständige Adresse",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["adresse", "anschrift", "wohnort", "address"],
        example="Musterstraße 1, 10115 Berlin",
    ),
    "street": FieldDefinition(
        key="street",
        label_en="Street",
        label_de="Straße",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["straße", "strasse", "street name"],
        example="Musterstraße",
    ),
    "house_number": FieldDefinition(
        key="house_number",
        label_en="House Number",
        label_de="Hausnummer",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["hausnummer", "haus-nr", "nr."],
        regex=r"\d+[a-zA-Z]?",
        example="12a",
    ),
    "postal_code": FieldDefinition(
        key="postal_code",
        label_en="Postal Code",
        label_de="Postleitzahl",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["postleitzahl", "plz", "zip code", "code postal"],
        regex=r"\d{5}",
        example="10115",
    ),
    "city": FieldDefinition(
        key="city",
        label_en="City",
        label_de="Stadt",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["stadt", "ort", "wohnort", "city", "ville"],
        example="Berlin",
    ),
    "district": FieldDefinition(
        key="district",
        label_en="District",
        label_de="Stadtteil",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["stadtteil", "bezirk", "ortsteil"],
    ),
    "state": FieldDefinition(
        key="state",
        label_en="State / Bundesland",
        label_de="Bundesland",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["bundesland", "land", "state", "région"],
        example="Berlin / Bayern / NRW",
    ),
    "country": FieldDefinition(
        key="country",
        label_en="Country",
        label_de="Land",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["land", "country", "pays"],
        example="Deutschland",
    ),
    "address_supplement": FieldDefinition(
        key="address_supplement",
        label_en="Address Supplement",
        label_de="Adresszusatz",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["adresszusatz", "c/o", "apartment", "wohnung"],
        example="c/o Mustermann / Wohnung 3",
    ),
    "po_box": FieldDefinition(
        key="po_box",
        label_en="PO Box",
        label_de="Postfach",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["postfach", "p.o. box"],
    ),
    "registration_date": FieldDefinition(
        key="registration_date",
        label_en="Registration Date",
        label_de="Anmeldedatum",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["anmeldedatum", "datum der anmeldung"],
    ),
    "deregistration_date": FieldDefinition(
        key="deregistration_date",
        label_en="Deregistration Date",
        label_de="Abmeldedatum",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["abmeldedatum", "datum der abmeldung"],
    ),
    "previous_address": FieldDefinition(
        key="previous_address",
        label_en="Previous Address",
        label_de="Vorherige Adresse",
        category=FieldCategory.ADDRESS,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["vorherige adresse", "letzte anschrift", "previous address"],
    ),
    # ── CONTACT ───────────────────────────────────────────────────────────────
    "phone_personal": FieldDefinition(
        key="phone_personal",
        label_en="Personal Phone",
        label_de="Persönliche Telefonnummer",
        category=FieldCategory.CONTACT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["telefon", "handy", "mobil", "phone", "tel"],
        regex=r"(\+49|0)[0-9\s\-/]{9,15}",
        example="+49 170 1234567",
    ),
    "phone_work": FieldDefinition(
        key="phone_work",
        label_en="Work Phone",
        label_de="Geschäftliche Telefonnummer",
        category=FieldCategory.CONTACT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["geschäftstelefon", "work phone", "büro"],
    ),
    "phone_emergency": FieldDefinition(
        key="phone_emergency",
        label_en="Emergency Phone",
        label_de="Notfallkontakt",
        category=FieldCategory.CONTACT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["notfallkontakt", "emergency contact"],
    ),
    "fax": FieldDefinition(
        key="fax",
        label_en="Fax",
        label_de="Faxnummer",
        category=FieldCategory.CONTACT,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["fax", "telefax"],
    ),
    "email_primary": FieldDefinition(
        key="email_primary",
        label_en="Primary Email",
        label_de="Haupt-E-Mail",
        category=FieldCategory.CONTACT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["e-mail", "email", "e-mail-adresse"],
        regex=r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}",
        example="max.mustermann@email.de",
    ),
    "email_secondary": FieldDefinition(
        key="email_secondary",
        label_en="Secondary Email",
        label_de="Zweite E-Mail",
        category=FieldCategory.CONTACT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["zweite e-mail", "alternative email"],
    ),
    "website": FieldDefinition(
        key="website",
        label_en="Website",
        label_de="Webseite",
        category=FieldCategory.CONTACT,
        sensitivity=FieldSensitivity.PUBLIC,
        aliases=["webseite", "homepage", "url"],
    ),
    # ── BANKING ───────────────────────────────────────────────────────────────
    "iban": FieldDefinition(
        key="iban",
        label_en="IBAN",
        label_de="IBAN",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["iban", "kontonummer", "bankverbindung"],
        regex=r"[A-Z]{2}\d{2}[A-Z0-9]{4}\d{7}([A-Z0-9]?){0,16}",
        example="DE89 3704 0044 0532 0130 00",
    ),
    "bic": FieldDefinition(
        key="bic",
        label_en="BIC / SWIFT",
        label_de="BIC",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["bic", "swift", "bankleitzahl"],
        regex=r"[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?",
        example="COBADEFFXXX",
    ),
    "bank_name": FieldDefinition(
        key="bank_name",
        label_en="Bank Name",
        label_de="Bankname",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["bank", "kreditinstitut", "geldinstitut"],
        example="Deutsche Bank / Sparkasse / Commerzbank",
    ),
    "account_number": FieldDefinition(
        key="account_number",
        label_en="Account Number",
        label_de="Kontonummer",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["kontonummer", "konto-nr"],
    ),
    "bank_routing_number": FieldDefinition(
        key="bank_routing_number",
        label_en="Bank Routing Number",
        label_de="Bankleitzahl",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["bankleitzahl", "blz"],
        regex=r"\d{8}",
    ),
    "account_type": FieldDefinition(
        key="account_type",
        label_en="Account Type",
        label_de="Kontotyp",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["kontotyp", "girokonto", "sparkonto", "tagesgeld"],
        example="Girokonto / Sparkonto / Tagesgeldkonto",
    ),
    "account_holder": FieldDefinition(
        key="account_holder",
        label_en="Account Holder",
        label_de="Kontoinhaber",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["kontoinhaber", "account owner"],
    ),
    "balance": FieldDefinition(
        key="balance",
        label_en="Balance",
        label_de="Kontostand",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["kontostand", "saldo", "balance"],
        regex=r"-?\d{1,3}(\.\d{3})*(,\d{2})?\s?€",
    ),
    "statement_date": FieldDefinition(
        key="statement_date",
        label_en="Statement Date",
        label_de="Kontoauszugsdatum",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["kontoauszugsdatum", "auszugsdatum"],
    ),
    "credit_limit": FieldDefinition(
        key="credit_limit",
        label_en="Credit Limit",
        label_de="Kreditlimit",
        category=FieldCategory.BANKING,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["kreditlimit", "verfügungsrahmen", "dispokredit"],
    ),
    # ── FINANCIAL ─────────────────────────────────────────────────────────────
    "gross_amount": FieldDefinition(
        key="gross_amount",
        label_en="Gross Amount",
        label_de="Bruttobetrag",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["brutto", "bruttolohn", "bruttogehalt", "gross salary"],
        regex=r"\d{1,3}(\.\d{3})*(,\d{2})?\s?€",
    ),
    "net_amount": FieldDefinition(
        key="net_amount",
        label_en="Net Amount",
        label_de="Nettobetrag",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=[
            "netto",
            "nettolohn",
            "nettogehalt",
            "net salary",
            "auszahlungsbetrag",
        ],
        regex=r"\d{1,3}(\.\d{3})*(,\d{2})?\s?€",
    ),
    "pay_date": FieldDefinition(
        key="pay_date",
        label_en="Pay Date",
        label_de="Auszahlungsdatum",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["auszahlungsdatum", "zahlungsdatum", "pay date"],
    ),
    "pay_period": FieldDefinition(
        key="pay_period",
        label_en="Pay Period",
        label_de="Abrechnungszeitraum",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["abrechnungszeitraum", "abrechnungsmonat"],
        example="Januar 2025 / 01.2025",
    ),
    "hourly_rate": FieldDefinition(
        key="hourly_rate",
        label_en="Hourly Rate",
        label_de="Stundenlohn",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["stundenlohn", "stundensatz", "hourly wage"],
    ),
    "working_hours": FieldDefinition(
        key="working_hours",
        label_en="Working Hours",
        label_de="Arbeitsstunden",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["arbeitsstunden", "wochenstunden", "stunden"],
    ),
    "overtime_hours": FieldDefinition(
        key="overtime_hours",
        label_en="Overtime Hours",
        label_de="Überstunden",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["überstunden", "mehrarbeit"],
    ),
    "bonus": FieldDefinition(
        key="bonus",
        label_en="Bonus",
        label_de="Bonus / Prämie",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["bonus", "prämie", "sonderzahlung", "weihnachtsgeld"],
    ),
    "vacation_pay": FieldDefinition(
        key="vacation_pay",
        label_en="Vacation Pay",
        label_de="Urlaubsgeld",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["urlaubsgeld", "urlaubsabgeltung"],
    ),
    "deductions": FieldDefinition(
        key="deductions",
        label_en="Deductions",
        label_de="Abzüge",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["abzüge", "einbehalte", "lohnabzüge"],
    ),
    "income_tax": FieldDefinition(
        key="income_tax",
        label_en="Income Tax",
        label_de="Lohnsteuer",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["lohnsteuer", "einkommensteuer", "income tax"],
    ),
    "solidarity_surcharge": FieldDefinition(
        key="solidarity_surcharge",
        label_en="Solidarity Surcharge",
        label_de="Solidaritätszuschlag",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["solidaritätszuschlag", "soli"],
    ),
    "church_tax": FieldDefinition(
        key="church_tax",
        label_en="Church Tax",
        label_de="Kirchensteuer",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["kirchensteuer"],
    ),
    "health_insurance_contribution": FieldDefinition(
        key="health_insurance_contribution",
        label_en="Health Insurance Contribution",
        label_de="Krankenversicherungsbeitrag",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["krankenversicherungsbeitrag", "kv-beitrag"],
    ),
    "pension_contribution": FieldDefinition(
        key="pension_contribution",
        label_en="Pension Contribution",
        label_de="Rentenversicherungsbeitrag",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["rentenversicherungsbeitrag", "rv-beitrag"],
    ),
    "unemployment_insurance": FieldDefinition(
        key="unemployment_insurance",
        label_en="Unemployment Insurance",
        label_de="Arbeitslosenversicherung",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["arbeitslosenversicherungsbeitrag", "av-beitrag"],
    ),
    "long_term_care_insurance": FieldDefinition(
        key="long_term_care_insurance",
        label_en="Long-Term Care Insurance",
        label_de="Pflegeversicherung",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["pflegeversicherungsbeitrag", "pv-beitrag"],
    ),
    "annual_income": FieldDefinition(
        key="annual_income",
        label_en="Annual Income",
        label_de="Jahreseinkommen",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["jahreseinkommen", "jahresgehalt", "annual salary"],
    ),
    "invoice_number": FieldDefinition(
        key="invoice_number",
        label_en="Invoice Number",
        label_de="Rechnungsnummer",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["rechnungsnummer", "rechnung-nr", "invoice no"],
        regex=r"[A-Z0-9\-/]{4,20}",
    ),
    "invoice_date": FieldDefinition(
        key="invoice_date",
        label_en="Invoice Date",
        label_de="Rechnungsdatum",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["rechnungsdatum", "datum der rechnung"],
    ),
    "invoice_amount": FieldDefinition(
        key="invoice_amount",
        label_en="Invoice Amount",
        label_de="Rechnungsbetrag",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["rechnungsbetrag", "gesamtbetrag", "total"],
    ),
    "vat_number": FieldDefinition(
        key="vat_number",
        label_en="VAT Number",
        label_de="Umsatzsteuer-ID",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["umsatzsteuer-id", "ust-id", "vat id"],
        regex=r"DE\d{9}",
    ),
    "vat_amount": FieldDefinition(
        key="vat_amount",
        label_en="VAT Amount",
        label_de="Mehrwertsteuerbetrag",
        category=FieldCategory.FINANCIAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["mehrwertsteuer", "mwst", "ust", "vat"],
    ),
    # ── TAX ───────────────────────────────────────────────────────────────────
    "tax_id": FieldDefinition(
        key="tax_id",
        label_en="Tax ID",
        label_de="Steueridentifikationsnummer",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.CRITICAL,
        frozen=True,
        aliases=["steueridentifikationsnummer", "steuer-id", "steuer id", "tin"],
        regex=r"\d{11}",
        example="12 345 678 901",
    ),
    "tax_number": FieldDefinition(
        key="tax_number",
        label_en="Tax Number",
        label_de="Steuernummer",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["steuernummer", "steuer-nr", "tax no"],
        regex=r"\d{2,3}/\d{3}/\d{4,5}",
    ),
    "tax_class": FieldDefinition(
        key="tax_class",
        label_en="Tax Class",
        label_de="Steuerklasse",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["steuerklasse", "lohnsteuerklasse"],
        example="I / II / III / IV / V / VI",
    ),
    "tax_year": FieldDefinition(
        key="tax_year",
        label_en="Tax Year",
        label_de="Steuerjahr",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["steuerjahr", "veranlagungszeitraum"],
        regex=r"20\d{2}",
    ),
    "taxable_income": FieldDefinition(
        key="taxable_income",
        label_en="Taxable Income",
        label_de="Zu versteuerndes Einkommen",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["zu versteuerndes einkommen", "zvE"],
    ),
    "tax_amount": FieldDefinition(
        key="tax_amount",
        label_en="Tax Amount",
        label_de="Steuerbetrag",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["steuerbetrag", "festgesetzte steuer"],
    ),
    "tax_refund": FieldDefinition(
        key="tax_refund",
        label_en="Tax Refund",
        label_de="Steuererstattung",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["steuererstattung", "erstattungsbetrag"],
    ),
    "tax_payment_due": FieldDefinition(
        key="tax_payment_due",
        label_en="Tax Payment Due",
        label_de="Nachzahlung",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["nachzahlung", "steuernachzahlung"],
    ),
    "finanzamt": FieldDefinition(
        key="finanzamt",
        label_en="Tax Office",
        label_de="Finanzamt",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["finanzamt", "tax office", "steueramt"],
    ),
    "child_allowance": FieldDefinition(
        key="child_allowance",
        label_en="Child Allowance",
        label_de="Kinderfreibetrag",
        category=FieldCategory.TAX,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["kinderfreibetrag", "kindergeld"],
    ),
    # ── SOCIAL SECURITY ───────────────────────────────────────────────────────
    "social_security_number": FieldDefinition(
        key="social_security_number",
        label_en="Social Security Number",
        label_de="Sozialversicherungsnummer",
        category=FieldCategory.SOCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        frozen=True,
        aliases=[
            "sozialversicherungsnummer",
            "sv-nummer",
            "rentenversicherungsnummer",
            "kvnr",
        ],
        regex=r"\d{2}\d{6}[A-Z]\d{3}",
        example="65 070893 M 002",
    ),
    "health_insurance_number": FieldDefinition(
        key="health_insurance_number",
        label_en="Health Insurance Number",
        label_de="Krankenversicherungsnummer",
        category=FieldCategory.SOCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["krankenversicherungsnummer", "kvnr", "versichertennummer"],
        regex=r"[A-Z]\d{9}",
    ),
    "health_insurance_provider": FieldDefinition(
        key="health_insurance_provider",
        label_en="Health Insurance Provider",
        label_de="Krankenkasse",
        category=FieldCategory.SOCIAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["krankenkasse", "krankenversicherung", "kasse"],
        example="AOK / TK / Barmer / DAK",
    ),
    "pension_insurance_number": FieldDefinition(
        key="pension_insurance_number",
        label_en="Pension Insurance Number",
        label_de="Rentenversicherungsnummer",
        category=FieldCategory.PENSION,
        sensitivity=FieldSensitivity.CRITICAL,
        frozen=True,
        aliases=["rentenversicherungsnummer", "rv-nummer"],
    ),
    "unemployment_benefit_number": FieldDefinition(
        key="unemployment_benefit_number",
        label_en="Unemployment Benefit Number",
        label_de="Kundennummer Arbeitsagentur",
        category=FieldCategory.SOCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["kundennummer", "arbeitsagentur", "jobcenter"],
    ),
    "jobcenter_id": FieldDefinition(
        key="jobcenter_id",
        label_en="Jobcenter ID",
        label_de="Jobcenter-Kundennummer",
        category=FieldCategory.SOCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["jobcenter kundennummer", "sgb ii nummer"],
    ),
    "child_benefit_number": FieldDefinition(
        key="child_benefit_number",
        label_en="Child Benefit Number",
        label_de="Kindergeldnummer",
        category=FieldCategory.SOCIAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["kindergeldnummer", "familienkasse"],
    ),
    # ── EMPLOYMENT ────────────────────────────────────────────────────────────
    "employer": FieldDefinition(
        key="employer",
        label_en="Employer",
        label_de="Arbeitgeber",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["arbeitgeber", "firma", "unternehmen", "employer", "company"],
        example="Musterfirma GmbH",
    ),
    "employer_address": FieldDefinition(
        key="employer_address",
        label_en="Employer Address",
        label_de="Arbeitgeberadresse",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["arbeitgeberadresse", "firmenadresse"],
    ),
    "employer_tax_number": FieldDefinition(
        key="employer_tax_number",
        label_en="Employer Tax Number",
        label_de="Betriebsnummer",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["betriebsnummer", "arbeitgebernummer"],
        regex=r"\d{8}",
    ),
    "job_title": FieldDefinition(
        key="job_title",
        label_en="Job Title",
        label_de="Berufsbezeichnung",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["berufsbezeichnung", "stelle", "position", "job title"],
        example="Softwareentwickler / Buchhalter",
    ),
    "employment_type": FieldDefinition(
        key="employment_type",
        label_en="Employment Type",
        label_de="Beschäftigungsart",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["beschäftigungsart", "anstellungsart"],
        example="Vollzeit / Teilzeit / Minijob / Werkvertrag",
    ),
    "contract_start": FieldDefinition(
        key="contract_start",
        label_en="Contract Start",
        label_de="Vertragsbeginn",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["vertragsbeginn", "eintrittsdatum", "beschäftigt seit"],
    ),
    "contract_end": FieldDefinition(
        key="contract_end",
        label_en="Contract End",
        label_de="Vertragsende",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        has_expiry=True,
        aliases=["vertragsende", "befristet bis", "austritt"],
    ),
    "probation_end": FieldDefinition(
        key="probation_end",
        label_en="Probation End",
        label_de="Probezeit Ende",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        has_expiry=True,
        aliases=["probezeit", "probezeit ende"],
    ),
    "vacation_days": FieldDefinition(
        key="vacation_days",
        label_en="Vacation Days",
        label_de="Urlaubstage",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["urlaubstage", "jahresurlaub"],
        example="30 Tage",
    ),
    "notice_period": FieldDefinition(
        key="notice_period",
        label_en="Notice Period",
        label_de="Kündigungsfrist",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["kündigungsfrist", "notice period"],
        example="4 Wochen zum Monatsende",
    ),
    "department": FieldDefinition(
        key="department",
        label_en="Department",
        label_de="Abteilung",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["abteilung", "fachbereich", "department"],
    ),
    "cost_center": FieldDefinition(
        key="cost_center",
        label_en="Cost Center",
        label_de="Kostenstelle",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["kostenstelle"],
    ),
    "personnel_number": FieldDefinition(
        key="personnel_number",
        label_en="Personnel Number",
        label_de="Personalnummer",
        category=FieldCategory.EMPLOYMENT,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["personalnummer", "mitarbeiternummer"],
    ),
    # ── PROPERTY / RENTAL ─────────────────────────────────────────────────────
    "landlord": FieldDefinition(
        key="landlord",
        label_en="Landlord",
        label_de="Vermieter",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["vermieter", "eigentümer", "landlord"],
    ),
    "landlord_address": FieldDefinition(
        key="landlord_address",
        label_en="Landlord Address",
        label_de="Vermieteradresse",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["vermieteradresse"],
    ),
    "rent_amount": FieldDefinition(
        key="rent_amount",
        label_en="Rent Amount",
        label_de="Mietbetrag",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["kaltmiete", "warmmiete", "miete", "rent"],
        regex=r"\d{1,4}(,\d{2})?\s?€",
    ),
    "warm_rent": FieldDefinition(
        key="warm_rent",
        label_en="Warm Rent",
        label_de="Warmmiete",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["warmmiete", "gesamtmiete"],
    ),
    "cold_rent": FieldDefinition(
        key="cold_rent",
        label_en="Cold Rent",
        label_de="Kaltmiete",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["kaltmiete", "grundmiete"],
    ),
    "utilities": FieldDefinition(
        key="utilities",
        label_en="Utilities",
        label_de="Nebenkosten",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["nebenkosten", "betriebskosten"],
    ),
    "deposit": FieldDefinition(
        key="deposit",
        label_en="Deposit",
        label_de="Kaution",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["kaution", "mietkaution", "deposit"],
    ),
    "floor_area": FieldDefinition(
        key="floor_area",
        label_en="Floor Area",
        label_de="Wohnfläche",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["wohnfläche", "nutzfläche", "fläche"],
        regex=r"\d{1,3}(,\d{1,2})?\s?m²",
        example="65,5 m²",
    ),
    "floor_number": FieldDefinition(
        key="floor_number",
        label_en="Floor Number",
        label_de="Stockwerk",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["stockwerk", "etage", "obergeschoss"],
    ),
    "property_type": FieldDefinition(
        key="property_type",
        label_en="Property Type",
        label_de="Wohnungstyp",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["wohnungstyp", "immobilientyp"],
        example="Wohnung / Haus / WG-Zimmer",
    ),
    "number_of_rooms": FieldDefinition(
        key="number_of_rooms",
        label_en="Number of Rooms",
        label_de="Zimmeranzahl",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["zimmeranzahl", "zimmer", "rooms"],
        example="2,5 Zimmer",
    ),
    "property_id": FieldDefinition(
        key="property_id",
        label_en="Property ID",
        label_de="Objekt-ID",
        category=FieldCategory.PROPERTY,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["objekt-id", "objektnummer"],
    ),
    # ── INSURANCE ─────────────────────────────────────────────────────────────
    "policy_number": FieldDefinition(
        key="policy_number",
        label_en="Policy Number",
        label_de="Versicherungsscheinnummer",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["versicherungsscheinnummer", "policennummer", "versicherungsnummer"],
    ),
    "insurance_type": FieldDefinition(
        key="insurance_type",
        label_en="Insurance Type",
        label_de="Versicherungsart",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["versicherungsart", "versicherungstyp"],
        example="Kranken / Haftpflicht / Hausrat / KFZ / Lebens",
    ),
    "insurance_provider": FieldDefinition(
        key="insurance_provider",
        label_en="Insurance Provider",
        label_de="Versicherungsgesellschaft",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["versicherungsgesellschaft", "versicherer", "anbieter"],
        example="Allianz / HUK / ERGO / AXA",
    ),
    "insurance_start": FieldDefinition(
        key="insurance_start",
        label_en="Insurance Start",
        label_de="Versicherungsbeginn",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["versicherungsbeginn", "vertragsbeginn"],
    ),
    "insurance_end": FieldDefinition(
        key="insurance_end",
        label_en="Insurance End",
        label_de="Versicherungsende",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.SENSITIVE,
        has_expiry=True,
        aliases=["versicherungsende", "vertragsende", "ablaufdatum"],
    ),
    "premium": FieldDefinition(
        key="premium",
        label_en="Premium",
        label_de="Versicherungsprämie",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["versicherungsprämie", "beitrag", "jahresbeitrag", "monatsbeitrag"],
    ),
    "coverage_amount": FieldDefinition(
        key="coverage_amount",
        label_en="Coverage Amount",
        label_de="Versicherungssumme",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["versicherungssumme", "deckungssumme"],
    ),
    "deductible": FieldDefinition(
        key="deductible",
        label_en="Deductible",
        label_de="Selbstbeteiligung",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["selbstbeteiligung", "selbstbehalt", "franchise"],
    ),
    "beneficiary": FieldDefinition(
        key="beneficiary",
        label_en="Beneficiary",
        label_de="Begünstigter",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["begünstigter", "bezugsberechtigter"],
    ),
    "insurance_agent": FieldDefinition(
        key="insurance_agent",
        label_en="Insurance Agent",
        label_de="Versicherungsvertreter",
        category=FieldCategory.INSURANCE,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["versicherungsvertreter", "agent", "betreuer"],
    ),
    # ── EDUCATION ─────────────────────────────────────────────────────────────
    "institution": FieldDefinition(
        key="institution",
        label_en="Institution",
        label_de="Bildungseinrichtung",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["schule", "universität", "hochschule", "institution"],
        example="TU Berlin / Humboldt Universität",
    ),
    "degree": FieldDefinition(
        key="degree",
        label_en="Degree",
        label_de="Abschluss",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["abschluss", "titel", "degree"],
        example="Bachelor / Master / Diplom / Abitur",
    ),
    "field_of_study": FieldDefinition(
        key="field_of_study",
        label_en="Field of Study",
        label_de="Studiengang",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["studiengang", "fachrichtung", "major"],
    ),
    "graduation_date": FieldDefinition(
        key="graduation_date",
        label_en="Graduation Date",
        label_de="Abschlussdatum",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["abschlussdatum", "datum des abschlusses"],
    ),
    "enrollment_date": FieldDefinition(
        key="enrollment_date",
        label_en="Enrollment Date",
        label_de="Immatrikulationsdatum",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["immatrikulationsdatum", "einschreibedatum"],
    ),
    "student_id": FieldDefinition(
        key="student_id",
        label_en="Student ID",
        label_de="Matrikelnummer",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["matrikelnummer", "student id"],
    ),
    "grade": FieldDefinition(
        key="grade",
        label_en="Grade / GPA",
        label_de="Note",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["note", "gesamtnote", "abschlussnote", "gpa"],
        example="1,5 / sehr gut",
    ),
    "certificate_number": FieldDefinition(
        key="certificate_number",
        label_en="Certificate Number",
        label_de="Zeugnissnummer",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["zeugnissnummer", "urkundennummer"],
    ),
    "language_certificate": FieldDefinition(
        key="language_certificate",
        label_en="Language Certificate",
        label_de="Sprachzertifikat",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["sprachzertifikat", "sprachnachweis"],
        example="B2 / C1 / TestDaF / Goethe",
    ),
    "language_level": FieldDefinition(
        key="language_level",
        label_en="Language Level",
        label_de="Sprachniveau",
        category=FieldCategory.EDUCATION,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["sprachniveau", "sprachkenntnisse"],
        example="A1 / A2 / B1 / B2 / C1 / C2",
    ),
    # ── MEDICAL ───────────────────────────────────────────────────────────────
    "blood_type": FieldDefinition(
        key="blood_type",
        label_en="Blood Type",
        label_de="Blutgruppe",
        category=FieldCategory.MEDICAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["blutgruppe", "blood group"],
        example="A+ / B- / 0+ / AB+",
    ),
    "allergies": FieldDefinition(
        key="allergies",
        label_en="Allergies",
        label_de="Allergien",
        category=FieldCategory.MEDICAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["allergien", "unverträglichkeiten"],
    ),
    "chronic_conditions": FieldDefinition(
        key="chronic_conditions",
        label_en="Chronic Conditions",
        label_de="Chronische Erkrankungen",
        category=FieldCategory.MEDICAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["chronische erkrankungen", "vorerkrankungen"],
    ),
    "medications": FieldDefinition(
        key="medications",
        label_en="Medications",
        label_de="Medikamente",
        category=FieldCategory.MEDICAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["medikamente", "arzneimittel", "dauermedikation"],
    ),
    "doctor_name": FieldDefinition(
        key="doctor_name",
        label_en="Doctor Name",
        label_de="Arztname",
        category=FieldCategory.MEDICAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["arztname", "behandelnder arzt", "hausarzt"],
    ),
    "hospital": FieldDefinition(
        key="hospital",
        label_en="Hospital",
        label_de="Krankenhaus",
        category=FieldCategory.MEDICAL,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["krankenhaus", "klinik", "hospital"],
    ),
    "vaccination_record": FieldDefinition(
        key="vaccination_record",
        label_en="Vaccination Record",
        label_de="Impfausweis",
        category=FieldCategory.MEDICAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["impfausweis", "impfpass", "impfung"],
    ),
    "disability_degree": FieldDefinition(
        key="disability_degree",
        label_en="Disability Degree",
        label_de="Behinderungsgrad",
        category=FieldCategory.MEDICAL,
        sensitivity=FieldSensitivity.CRITICAL,
        aliases=["grad der behinderung", "gdb", "schwerbehindertenausweis"],
        regex=r"\d{2,3}\s?%",
    ),
    "disability_card_number": FieldDefinition(
        key="disability_card_number",
        label_en="Disability Card Number",
        label_de="Schwerbehindertenausweis-Nr",
        category=FieldCategory.MEDICAL,
        sensitivity=FieldSensitivity.CRITICAL,
        has_expiry=True,
        aliases=["schwerbehindertenausweis", "behindertenausweis"],
    ),
    # ── VEHICLE ───────────────────────────────────────────────────────────────
    "license_plate": FieldDefinition(
        key="license_plate",
        label_en="License Plate",
        label_de="Kennzeichen",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["kennzeichen", "nummerntafel", "license plate"],
    ),
    "vehicle_type": FieldDefinition(
        key="vehicle_type",
        label_en="Vehicle Type",
        label_de="Fahrzeugtyp",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["fahrzeugtyp", "auto", "pkw", "motorrad", "fahrzeug"],
    ),
    "vehicle_brand": FieldDefinition(
        key="vehicle_brand",
        label_en="Vehicle Brand",
        label_de="Fahrzeugmarke",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["fahrzeugmarke", "marke", "brand"],
    ),
    "vehicle_model": FieldDefinition(
        key="vehicle_model",
        label_en="Vehicle Model",
        label_de="Fahrzeugmodell",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["fahrzeugmodell", "modell", "model"],
    ),
    "vehicle_color": FieldDefinition(
        key="vehicle_color",
        label_en="Vehicle Color",
        label_de="Fahrzeugfarbe",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["fahrzeugfarbe", "farbe", "color"],
    ),
    "vehicle_vin": FieldDefinition(
        key="vehicle_vin",
        label_en="Vehicle Identification Number",
        label_de="Fahrgestellnummer",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["fahrgestellnummer", "vin", "chassis number"],
    ),
    "vehicle_registration_date": FieldDefinition(
        key="vehicle_registration_date",
        label_en="Vehicle Registration Date",
        label_de="Erstzulassungsdatum",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=["erstzulassungsdatum", "registration date"],
    ),
    "vehicle_insurance_policy_number": FieldDefinition(
        key="vehicle_insurance_policy_number",
        label_en="Vehicle Insurance Policy Number",
        label_de="Kfz-Versicherungsnummer",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=[
            "kfz-versicherungsnummer",
            "vehicle insurance number",
            "insurance policy number",
        ],
    ),
    "vehicle_insurance_expiry_date": FieldDefinition(
        key="vehicle_insurance_expiry_date",
        label_en="Vehicle Insurance Expiry Date",
        label_de="Kfz-Versicherungsablaufdatum",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=[
            "kfz-versicherungsablaufdatum",
            "vehicle insurance expiry date",
            "insurance expiry date",
        ],
    ),
    "vehicle_insurance_company": FieldDefinition(
        key="vehicle_insurance_company",
        label_en="Vehicle Insurance Company",
        label_de="Kfz-Versicherungsgesellschaft",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=[
            "kfz-versicherungsgesellschaft",
            "vehicle insurance company",
            "insurance company",
        ],
    ),
    "vehicle_insurance_agent": FieldDefinition(
        key="vehicle_insurance_agent",
        label_en="Vehicle Insurance Agent",
        label_de="Kfz-Versicherungsmakler",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=[
            "kfz-versicherungsmakler",
            "vehicle insurance agent",
            "insurance agent",
        ],
    ),
    "vehicle_insurance_agent_phone": FieldDefinition(
        key="vehicle_insurance_agent_phone",
        label_en="Vehicle Insurance Agent Phone",
        label_de="Kfz-Versicherungsmakler Telefonnummer",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=[
            "kfz-versicherungsmakler telefonnummer",
            "vehicle insurance agent phone",
            "insurance agent phone",
        ],
    ),
    "vehicle_insurance_agent_email": FieldDefinition(
        key="vehicle_insurance_agent_email",
        label_en="Vehicle Insurance Agent Email",
        label_de="Kfz-Versicherungsmakler E-Mail",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=[
            "kfz-versicherungsmakler e-mail",
            "vehicle insurance agent email",
            "insurance agent email",
        ],
    ),
    "vehicle_insurance_agent_address": FieldDefinition(
        key="vehicle_insurance_agent_address",
        label_en="Vehicle Insurance Agent Address",
        label_de="Kfz-Versicherungsmakler Adresse",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=[
            "kfz-versicherungsmakler adresse",
            "vehicle insurance agent address",
            "insurance agent address",
        ],
    ),
    "vehicle_insurance_agent_city": FieldDefinition(
        key="vehicle_insurance_agent_city",
        label_en="Vehicle Insurance Agent City",
        label_de="Kfz-Versicherungsmakler Stadt",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=[
            "kfz-versicherungsmakler stadt",
            "vehicle insurance agent city",
            "insurance agent city",
        ],
    ),
    "vehicle_insurance_agent_postal_code": FieldDefinition(
        key="vehicle_insurance_agent_postal_code",
        label_en="Vehicle Insurance Agent Postal Code",
        label_de="Kfz-Versicherungsmakler Postleitzahl",
        category=FieldCategory.VEHICLE,
        sensitivity=FieldSensitivity.SENSITIVE,
        aliases=[
            "kfz-versicherungsmakler postleitzahl",
            "vehicle insurance agent postal code",
            "insurance agent postal code",
        ],
    ),
    # ── OTHER ───────────────────────────────────────────────────────────────
    "notes": FieldDefinition(
        key="notes",
        label_en="Notes",
        label_de="Notizen",
        category=FieldCategory.OTHER,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["notizen", "bemerkungen", "notes"],
    ),
    # ── LEGACY / DEPRECATED ─────────────────────────────────────────────────
    "legacy_field": FieldDefinition(
        key="legacy_field",
        label_en="Legacy Field",
        label_de="Veraltetes Feld",
        category=FieldCategory.OTHER,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["veraltetes feld", "legacy field", "deprecated field"],
    ),
    # ── CUSTOM FIELDS (PLACEHOLDER) ───────────────────────────────────────────
    # Custom fields can be added dynamically by users, so we define a placeholder entry.
    "custom_field": FieldDefinition(
        key="custom_field",
        label_en="Custom Field",
        label_de="Benutzerdefiniertes Feld",
        category=FieldCategory.OTHER,
        sensitivity=FieldSensitivity.INTERNAL,
        aliases=["benutzerdefiniertes feld", "custom field", "user-defined field"],
    ),
    # ── ADDITIONAL FIELDS CAN BE ADDED HERE ─────────────────────────────────
}
