from __future__ import annotations

from enum import StrEnum


class KnowledgeFactType(StrEnum):
    PERSON_FIRST_NAME = "PERSON_FIRST_NAME"
    PERSON_LAST_NAME = "PERSON_LAST_NAME"
    PERSON_FULL_NAME = "PERSON_FULL_NAME"
    DATE_OF_BIRTH = "DATE_OF_BIRTH"
    PLACE_OF_BIRTH = "PLACE_OF_BIRTH"
    NATIONALITY = "NATIONALITY"
    ADDRESS_STREET = "ADDRESS_STREET"
    ADDRESS_HOUSE_NUMBER = "ADDRESS_HOUSE_NUMBER"
    ADDRESS_POSTAL_CODE = "ADDRESS_POSTAL_CODE"
    ADDRESS_CITY = "ADDRESS_CITY"
    ADDRESS_COUNTRY = "ADDRESS_COUNTRY"
    PHONE_NUMBER = "PHONE_NUMBER"
    EMAIL_ADDRESS = "EMAIL_ADDRESS"
    IBAN = "IBAN"
    BIC = "BIC"
    BANK_NAME = "BANK_NAME"
    TAX_ID = "TAX_ID"
    IDENTITY_CARD_NUMBER = "IDENTITY_CARD_NUMBER"
    PASSPORT_NUMBER = "PASSPORT_NUMBER"
    MARITAL_STATUS = "MARITAL_STATUS"
    EMPLOYER_NAME = "EMPLOYER_NAME"
    JOB_TITLE = "JOB_TITLE"
    DOCUMENT_DATE = "DOCUMENT_DATE"
    DOCUMENT_REFERENCE = "DOCUMENT_REFERENCE"
